###
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json

{
    "name": "blackcat",
    "color": "black",
    "birth_year": 2009
}

###
GET http://127.0.0.1:8000/cats/

###
PATCH http://127.0.0.1:8000/cats/1/ HTTP/1.1
content-type: application/json

{
    "name": "blackcat1",
    "color": "black1",
    "birth_year": 2009
}
