# Generated by Django 5.1.1 on 2026-01-17 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
